function [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% Returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: A table containing the same predictor and response
%       columns as those imported into the app.
%
%  Output:
%      trainedClassifier: A struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: A function to make predictions on new
%       data.
%
%      validationAccuracy: A double containing the accuracy as a
%       percentage. In the app, the Models pane displays this overall
%       accuracy score for each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   yfit = trainedClassifier.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 16-Jun-2022 16:41:29


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'Mitjana 1', 'Variança 1', 'Desviacio 1', 'GradientMag 1', 'Mitjana 2', 'Variança 2', 'Desviacio 2', 'GradientMag 2', 'Mitjana 3', 'Variança 3', 'Desviacio 3', 'GradientMag 3', 'Mitjana 4', 'Variança 4', 'Desviacio 4', 'GradientMag 4', 'Mitjana 5', 'Variança 5', 'Desviacio 5', 'GradientMag 5', 'Mitjana 6', 'Variança 6', 'Desviacio 6', 'GradientMag 6'};
predictors = inputTable(:, predictorNames);
response = inputTable.Deteccio;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Data transformation: Select subset of the features
% This code selects the same subset of features as were used in the app.
includedPredictorNames = predictors.Properties.VariableNames([true true true false true true true false true true true false true true true false true true true false true true true false]);
predictors = predictors(:,includedPredictorNames);
isCategoricalPredictor = isCategoricalPredictor([true true true false true true true false true true true false true true true false true true true false true true true false]);

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
classificationSVM = fitcsvm(...
    predictors, ...
    response, ...
    'KernelFunction', 'linear', ...
    'PolynomialOrder', [], ...
    'KernelScale', 'auto', ...
    'BoxConstraint', 1, ...
    'Standardize', true, ...
    'ClassNames', categorical({'Ulls'; 'No-Ulls'}, {'Ulls' 'No-Ulls'}));

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
featureSelectionFcn = @(x) x(:,includedPredictorNames);
svmPredictFcn = @(x) predict(classificationSVM, x);
trainedClassifier.predictFcn = @(x) svmPredictFcn(featureSelectionFcn(predictorExtractionFcn(x)));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'Desviacio 1', 'Desviacio 2', 'Desviacio 3', 'Desviacio 4', 'Desviacio 5', 'Desviacio 6', 'GradientMag 1', 'GradientMag 2', 'GradientMag 3', 'GradientMag 4', 'GradientMag 5', 'GradientMag 6', 'Mitjana 1', 'Mitjana 2', 'Mitjana 3', 'Mitjana 4', 'Mitjana 5', 'Mitjana 6', 'Variança 1', 'Variança 2', 'Variança 3', 'Variança 4', 'Variança 5', 'Variança 6'};
trainedClassifier.ClassificationSVM = classificationSVM;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2022a.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  yfit = c.predictFcn(T) \nreplacing ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'Mitjana 1', 'Variança 1', 'Desviacio 1', 'GradientMag 1', 'Mitjana 2', 'Variança 2', 'Desviacio 2', 'GradientMag 2', 'Mitjana 3', 'Variança 3', 'Desviacio 3', 'GradientMag 3', 'Mitjana 4', 'Variança 4', 'Desviacio 4', 'GradientMag 4', 'Mitjana 5', 'Variança 5', 'Desviacio 5', 'GradientMag 5', 'Mitjana 6', 'Variança 6', 'Desviacio 6', 'GradientMag 6'};
predictors = inputTable(:, predictorNames);
response = inputTable.Deteccio;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Perform cross-validation
partitionedModel = crossval(trainedClassifier.ClassificationSVM, 'KFold', 5);

% Compute validation predictions
[validationPredictions, validationScores] = kfoldPredict(partitionedModel);

% Compute validation accuracy
validationAccuracy = 1 - kfoldLoss(partitionedModel, 'LossFun', 'ClassifError');
